// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTest.EntityFrameworkTest;

namespace MyTest.Migrations
{
    [DbContext(typeof(BookContent))]
    [Migration("20190426123707_MyTest2")]
    partial class MyTest2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("MyTest.EntityFrameworkTest.Book", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("Code");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
